<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUklp85n\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUklp85n/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerUklp85n.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerUklp85n\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerUklp85n\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Uklp85n',
    'container.build_id' => '183d51c7',
    'container.build_time' => 1534061938,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerUklp85n');
